### ISSUE TITLE
Convert to new Swift syntax

### ISSUE THREAD

**Issue by emartinson** [Antondomashnev/ADChromePullToRefresh#1]
Hello, could you please convert the code to the latest Swift syntax? Can't fix some issues like
func setUpConstraints() in ADChromePullToRefreshActionView

```
    self.addConstraints(horizontalConstraints as [AnyObject])
```

gives: 'NSArray' is not implicitly convertible to '[AnyObject]'; did you mean to use 'as' to explicitly convert?

there is 'as' already. I can't get the root cause of the issue

**Comment by emartinson** [comment]
Fixed this by replacing this with:
self.addConstraints(horizontalConstraints as! [NSLayoutConstraint])

but there are more issues with linker I can't resolve:

Undefined symbols for architecture armv7:
  "ADChromePullToRefresh.ADChromePullToRefreshActionView.init (ADChromePullToRefresh.ADChromePullToRefreshActionView.Type)(coder : __ObjC.NSCoder) -> ADChromePullToRefresh.ADChromePullToRefreshActionView", referenced from:
      ADChromePullToRefresh.ADChromePullToRefreshCenterActionView.init (ADChromePullToRefresh.ADChromePullToRefreshCenterActionView.Type)(coder : __ObjC.NSCoder) -> ADChromePullToRefresh.ADChromePullToRefreshCenterActionView in ADChromePullToRefreshCenterActionView.o
      ADChromePullToRefresh.ADChromePullToRefreshLeftActionView.init (ADChromePullToRefresh.ADChromePullToRefreshLeftActionView.Type)(coder : __ObjC.NSCoder) -> ADChromePullToRefresh.ADChromePullToRefreshLeftActionView in ADChromePullToRefreshLeftActionView.o
      ADChromePullToRefresh.ADChromePullToRefreshRightActionView.init (ADChromePullToRefresh.ADChromePullToRefreshRightActionView.Type)(coder : __ObjC.NSCoder) -> ADChromePullToRefresh.ADChromePullToRefreshRightActionView in ADChromePullToRefreshRIghtActionView.o
ld: symbol(s) not found for architecture armv7

**Comment by Antondomashnev** [comment]
Hi @J-Crichton 

I will take a look on it soon. Please create an issue, it would be great, thanks.

**Comment by emartinson** [comment]
After a lot of time parsing swift code I've managed to fix and compile it, you may find class at https://yadi.sk/d/BqI86HDOm5qvH

Thank you very much for such a beautiful component!

**Comment by Antondomashnev** [comment]
@J-Crichton if you fix the code, please create PR so i can review your changes and merge them then
