### ISSUE TITLE
I have written project  in object-c. How can I use this framework in my project?

### ISSUE THREAD

**Issue by CXTretar** [Antondomashnev/ADChromePullToRefresh#5]

**Comment by Antondomashnev** [comment]
Hi @misscxuan, unfortunately, it won't work for the obj-c project as it's using some swift only feature.

**Comment by mattbarker016** [comment]
https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

Pretty sure you still can

**Comment by Antondomashnev** [comment]
@mattbarker016 thanks for the follow up, unfortunately the library contains some Swift only code such as structs, so i'd require to update many parts and it was not in the roadmap for the project.
